<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="derive" nsURI="http://www.sourcepit.org/emf/derive/1.0" nsPrefix="derive">
  <eClassifiers xsi:type="ecore:EClass" name="DerivationConfiguration" abstract="true"
      interface="true">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1">
      <eGenericType eTypeParameter="#//DerivationConfiguration/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="ecore" nsURI="http://www.sourcepit.org/emf/derive/ecore/1.0"
      nsPrefix="ecore">
    <eClassifiers xsi:type="ecore:EClass" name="EcoreDerivationConfiguration">
      <eGenericSuperTypes eClassifier="#//DerivationConfiguration">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
